- hosts: all
  tasks:
  - name:  "Update the repository cache and update package nginx to latest version using default release squeeze-backport"
    apt:
      name: nginx
      state: present
      update_cache: yes
  - name: start nginx service
    service:
      name: nginx
      state: started

